---
# Common role variables

# Default packages to install on all systems
common_packages:
  - htop
  - vim
  - curl
  - wget
  - unzip
  - git
  - python3-pip
  - awscli
  - jq
  - tree
  - ncdu
  - tmux
  - rsync
  - lsof
  - netstat-nat
  - tcpdump
  - ntp
  - ca-certificates
  - software-properties-common
  - apt-transport-https
  - gnupg2

# System configuration
system_timezone: "UTC"
ntp_servers:
  - "0.amazon.pool.ntp.org"
  - "1.amazon.pool.ntp.org"
  - "2.amazon.pool.ntp.org" 
  - "3.amazon.pool.ntp.org"

# Default system limits
system_limits:
  - domain: '*'
    type: soft
    item: nofile
    value: 65536
  - domain: '*'
    type: hard
    item: nofile
    value: 65536
  - domain: '*'
    type: soft
    item: nproc
    value: 4096
  - domain: '*'
    type: hard
    item: nproc
    value: 4096

# Sysctl parameters for performance and security
sysctl_parameters:
  # Network performance
  - name: net.core.rmem_max
    value: 134217728
  - name: net.core.wmem_max
    value: 134217728
  - name: net.ipv4.tcp_rmem
    value: "4096 87380 134217728"
  - name: net.ipv4.tcp_wmem
    value: "4096 65536 134217728"
  - name: net.core.netdev_max_backlog
    value: 5000
  - name: net.ipv4.tcp_congestion_control
    value: bbr
    
  # Security
  - name: net.ipv4.conf.all.send_redirects
    value: 0
  - name: net.ipv4.conf.default.send_redirects
    value: 0
  - name: net.ipv4.conf.all.accept_redirects
    value: 0
  - name: net.ipv4.conf.default.accept_redirects
    value: 0
  - name: net.ipv4.conf.all.secure_redirects
    value: 0
  - name: net.ipv4.conf.default.secure_redirects
    value: 0
  - name: net.ipv4.ip_forward
    value: 0
  - name: net.ipv4.conf.all.accept_source_route
    value: 0
  - name: net.ipv4.conf.default.accept_source_route
    value: 0
  - name: net.ipv4.conf.all.log_martians
    value: 1
  - name: net.ipv4.conf.default.log_martians
    value: 1
  - name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
  - name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
  - name: net.ipv4.tcp_syncookies
    value: 1
    
  # File system
  - name: fs.file-max
    value: 2097152
  - name: vm.swappiness
    value: 10
  - name: vm.dirty_ratio
    value: 15
  - name: vm.dirty_background_ratio
    value: 5

# Log rotation configurations
logrotate_configs:
  - name: applications
    logs:
      - "/var/log/applications/*.log"
    options:
      - daily
      - rotate 7
      - compress
      - delaycompress
      - missingok
      - notifempty
      - copytruncate
      - create 644 root root

# CloudWatch agent configuration
cloudwatch_config:
  agent:
    metrics_collection_interval: 60
    run_as_user: "cwagent"
  metrics:
    namespace: "{{ project_name }}/{{ environment }}"
    metrics_collected:
      cpu:
        measurement:
          - cpu_usage_idle
          - cpu_usage_iowait
          - cpu_usage_user
          - cpu_usage_system
        metrics_collection_interval: 60
        totalcpu: false
      disk:
        measurement:
          - used_percent
        metrics_collection_interval: 60
        resources:
          - "*"
      diskio:
        measurement:
          - io_time
          - read_bytes
          - write_bytes
          - reads
          - writes
        metrics_collection_interval: 60
        resources:
          - "*"
      mem:
        measurement:
          - mem_used_percent
        metrics_collection_interval: 60
      netstat:
        measurement:
          - tcp_established
          - tcp_time_wait
        metrics_collection_interval: 60
      swap:
        measurement:
          - swap_used_percent
        metrics_collection_interval: 60
  logs:
    logs_collected:
      files:
        collect_list:
          - file_path: "/var/log/syslog"
            log_group_name: "{{ project_name }}-{{ environment }}-syslog"
            log_stream_name: "{instance_id}"
            timezone: "UTC"
          - file_path: "/var/log/applications/*.log"
            log_group_name: "{{ project_name }}-{{ environment }}-applications"
            log_stream_name: "{instance_id}"
            timezone: "UTC"

# Unattended upgrades configuration
unattended_upgrades:
  origins_patterns:
    - 'origin=Ubuntu,archive=${distro_codename}-security'
    - 'origin=Ubuntu,archive=${distro_codename}-updates'
  auto_fix_interrupted_dpkg: true
  minimal_steps: true
  install_on_shutdown: false
  mail: ""
  mail_on_error: true
  remove_unused_dependencies: true
  automatic_reboot: false
  automatic_reboot_time: "02:00"

