---
# Web server specific variables

# Nginx configuration
nginx_user: www-data
nginx_worker_processes: auto
nginx_worker_connections: 1024
nginx_keepalive_timeout: 65
nginx_client_max_body_size: "10m"
nginx_server_tokens: "off"

# SSL/TLS configuration
ssl_protocols: "TLSv1.2 TLSv1.3"
ssl_prefer_server_ciphers: "off"
ssl_ciphers: >
  ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:
  ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:
  ECDHE-RSA-CHACHA20-POLY1305

# Security headers
security_headers:
  - "X-Frame-Options DENY"
  - "X-Content-Type-Options nosniff"
  - "X-XSS-Protection 1; mode=block"
  - "Referrer-Policy strict-origin-when-cross-origin"
  - "Content-Security-Policy default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:;"

# Gzip compression
nginx_gzip: "on"
nginx_gzip_vary: "on"
nginx_gzip_min_length: 1024
nginx_gzip_types: >
  text/plain
  text/css
  application/json
  application/javascript
  text/xml
  application/xml
  application/xml+rss
  text/javascript
  application/x-font-ttf
  font/opentype
  image/svg+xml
  image/x-icon

# Rate limiting
rate_limit_zone: "$binary_remote_addr zone=limit:10m rate=10r/s"
rate_limit_burst: 20
rate_limit_nodelay: true

# Application configuration
app_name: "iac-solution"
app_port: 3000
upstream_servers: "{{ groups['appservers'] | default(['127.0.0.1:3000']) }}"

# Health check configuration
health_check_port: 8080
health_check_url: "/health"
enable_nginx_status: true
nginx_status_allow_ips:
  - "127.0.0.1"
  - "{{ vpc_cidr | default('10.0.0.0/16') }}"

# Log configuration
access_log_format: 'main'
error_log_level: 'warn'
nginx_log_retention_days: 30
nginx_log_compress: true

# Performance tuning
worker_rlimit_nofile: 65535
use_epoll: true
multi_accept: "on"
sendfile: "on"
tcp_nopush: "on"
tcp_nodelay: "on"

# Cache configuration
open_file_cache: "max=200000 inactive=20s"
open_file_cache_valid: "30s"
open_file_cache_min_uses: 2
open_file_cache_errors: "on"

# SSL session configuration
ssl_session_cache: "shared:SSL:10m"
ssl_session_timeout: "10m"
ssl_session_tickets: "off"

# Additional web server packages
web_packages:
  - nginx-extras
  - ssl-cert
  - python3-certbot-nginx

# Monitoring
enable_nginx_prometheus_exporter: true
prometheus_exporter_port: 9113

# Firewall rules specific to web servers
web_firewall_rules:
  - port: 80
    proto: tcp
    rule: allow
  - port: 443
    proto: tcp
    rule: allow
  - port: "{{ health_check_port }}"
    proto: tcp
    rule: allow
    src: "{{ vpc_cidr | default('10.0.0.0/16') }}"
