---
# Application server handlers

- name: restart app
  systemd:
    name: "{{ app_name }}"
    state: restarted
    daemon_reload: yes
  listen: "restart app"

- name: reload app
  shell: |
    su - {{ app_user }} -c "pm2 reload {{ app_name }}"
  listen: "reload app"

- name: start app
  systemd:
    name: "{{ app_name }}"
    state: started
    enabled: yes
  listen: "start app"

- name: stop app
  systemd:
    name: "{{ app_name }}"
    state: stopped
  listen: "stop app"

- name: install npm dependencies
  npm:
    path: "{{ app_home }}"
    state: present
  become_user: "{{ app_user }}"
  listen: "install npm dependencies"

- name: reload systemd
  systemd:
    daemon_reload: yes
  listen: "reload systemd"

- name: restart amazon-cloudwatch-agent
  systemd:
    name: amazon-cloudwatch-agent
    state: restarted
    daemon_reload: yes
  listen: "restart amazon-cloudwatch-agent"

